feature: Make usable without atty.
colored-rs/colored pull request #134
Opened 2023-06-09 09:09 UTC by shanecelis

I'm thinking about using this crate with bevy for doing colored text without any tty in sight. This merely adds a feature 'tty' that is by default on, so no change unless opted-in.

2023-07-03 13:07 UTC, hwittenborn requested changes

2023-07-03 13:07 UTC, hwittenborn commented on src/control.rs
> +        }
The `Option` could just be removed, right?

```rust
        #[allow(unused_mut)]
        let mut tty = false;

        #[cfg(feature = "tty")]
        {
            tty = atty::is(atty::Stream::Stdout);
        }
```

2023-07-03 13:10 UTC, hwittenborn commented
Ignore the CI failing, that's due to all the features not being enabled. I'll get that fix shortly.

2023-07-05 01:36 UTC, hwittenborn commented
Hey, @shanecelis, I've gone ahead and replaced `atty` with `is-terminal` in the latest release because of #131. If you could get this PR moved over to that I'd still be more than glad to accept it :)

2023-07-05 02:23 UTC, shanecelis commented
Great. Will do.

2023-11-22 05:15 UTC, closed without merging