feat: impl `From<(r, g, b)>` to `CustomColor`
colored-rs/colored pull request #153
Opened 2023-10-24 09:56 UTC by caojen

Hi, this pull request implements `From<(u8, u8, u8)> for CustomColor`.

By this, we have one more way to create a `ColoredString` when using RGB:
```rust
"Hello".true_color(0, 255, 255);
"Hello".custom_color(CustomColor { 0, 255, 255 });

// new:
"Hello".custom_color((0, 255, 255)); 
```

2023-12-09 23:35 UTC, kurtlawrence requested changes

2023-12-09 23:35 UTC, kurtlawrence commented on .gitignore
> +.vscode
Don't include these changes.

2023-12-10 04:10 UTC, caojen commented
@kurtlawrence Ok.

2023-12-11 02:00 UTC, kurtlawrence approved these changes

2023-12-11 02:00 UTC, kurtlawrence commented
PR approved, I'll merge in once the CI runs through.

2023-12-11 02:07 UTC, merged