Add support for arbitrary ANSI color
colored-rs/colored pull request #166
Opened 2024-02-26 11:54 UTC by Asthowen

Add `ansi_color` and `on_ansi_color` on `Colorize` trait.

2024-02-26 23:06 UTC, kurtlawrence requested changes
Please add a changelog entry under breaking changes

2024-02-27 22:09 UTC, kurtlawrence approved these changes

2025-01-14 18:03 UTC, Asthowen commented
It's done 👍.

2025-04-04 14:33 UTC, Asthowen commented
Hello,
Are you still interested in this PR or can I close it?

2025-04-04 16:09 UTC, spenserblack approved these changes
LGTM!

2025-04-04 16:09 UTC, spenserblack commented on src/color.rs
> +            Self::AnsiColor(code) => format!("38;5;{code}").into(),
Slight nitpick: put this above `TrueColor`, so that the order goes from least specific to most specific coloring.

2025-04-04 16:52 UTC, Asthowen commented on src/color.rs
> +            Self::AnsiColor(code) => format!("38;5;{code}").into(),
It's done :+1:

2025-04-04 17:52 UTC, spenserblack commented
Thanks, sorry for the wait! I think I'll make a new release soon. Feel free to ping me if I'm taking too long :sweat_smile:

2025-04-04 17:53 UTC, merged